{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bms.fullname" . }}-backend-config
  labels:
    {{- include "bms.backend.labels" . | nindent 4 }}
data:
  FILE_UPLOAD_DIR: {{ .Values.backend.env.FILE_UPLOAD_DIR | quote }}
  SMTP_SERVER: {{ .Values.backend.env.SMTP_SERVER | quote }}
  SMTP_PORT: {{ .Values.backend.env.SMTP_PORT | quote }}
  FRONTEND_URL: {{ .Values.backend.env.FRONTEND_URL | quote }}
{{- end }}






