{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bms.fullname" . }}-backend-secret
  labels:
    {{- include "bms.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.secretEnv.DATABASE_URL | quote }}
  JWT_SECRET_KEY: {{ .Values.backend.secretEnv.JWT_SECRET_KEY | quote }}
  SUPER_ADMIN_EMAIL: {{ .Values.backend.secretEnv.SUPER_ADMIN_EMAIL | quote }}
  SUPER_ADMIN_PASSWORD: {{ .Values.backend.secretEnv.SUPER_ADMIN_PASSWORD | quote }}
  SUPER_ADMIN_NAME: {{ .Values.backend.secretEnv.SUPER_ADMIN_NAME | quote }}
  CORS_ORIGINS: {{ .Values.backend.secretEnv.CORS_ORIGINS | quote }}
  SMTP_USERNAME: {{ .Values.backend.secretEnv.SMTP_USERNAME | quote }}
  SMTP_PASSWORD: {{ .Values.backend.secretEnv.SMTP_PASSWORD | quote }}
{{- end }}



