---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: project-manager-bms-frontend
  labels:
    app: project-manager-bms
    component: frontend
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: project-manager-bms
    meta.helm.sh/release-namespace: at-yossi-dev
spec:
  to:
    kind: Service
    name: project-manager-bms-frontend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: project-manager-bms-backend
  labels:
    app: project-manager-bms
    component: backend
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: project-manager-bms
    meta.helm.sh/release-namespace: at-yossi-dev
spec:
  to:
    kind: Service
    name: project-manager-bms-backend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect